project:
  type: website
  output-dir: _site
  resources:
    - "content/slides/*.html"
    - "content/slides/css/**"
    - "content/slides/images/**"
    - "content/slides/r-scripts/**"
  render:
    - "*.qmd"
    - "content/**/*.qmd"
    - "!.claude/**"
    - "!CLAUDE.md"

lang: pt

publish:
  method: gh-pages
  repo: FCopf/prob-est-2026

website:
  page-navigation: true
  title: "5290 - PROBABILIDADE E ESTATÍSTICA"
  description: "Materiais, cronograma e recursos da UC Probabilidade e Estatística do Bict Mar — Unifesp."
  site-url: "https://fcopf.github.io/prob-est-2026"

  repo-url: "https://github.com/FCopf/prob-est-2026"
  open-graph: true

  page-footer:
    right: "BACHARELADO INTERDISCIPLINAR EM CIÊNCIA E TECNOLOGIA DO MAR — Bict Mar — Unifesp"
    left: Fabio Cop
    background: "#296354"

  sidebar: 
    background: "#3b8170"
    logo: "images/logo.png"
    style: "docked"
    search: true
    align: center
    tools:
      - icon: github
        href: https://github.com/FCopf/prob-est-2026
        text: GitHub da UC
      - icon: book
        href: https://moodlegrad.unifesp.br/
        text: Moodle Graduação
      - icon: terminal
        href: https://colab.research.google.com/drive/
        text: Google Colab
    
    collapse-level: 1
    contents:
      - section: "Informações do curso"
        contents:
          - href: course-info/syllabus.qmd
            text: Plano de Ensino
          - href: index.qmd
            text: Cronograma
          - href: course-info/bibliography.qmd
            text: Bibliografia e Links Úteis
      - section: "Leitura Prévia"
        contents:
          - href: content/pre-reading/pread-01-golem-de-praga.qmd
            text: "Aula 1 - O Golem de Praga"
          - href: content/pre-reading/pread-02-mundos-pequenos-mundos-grandes.qmd
            text: "Aula 2 - Mundos Pequenos e Mundos Grandes"
      - section: "Slides"
        contents:
          - href: content/slides/slides-01-contrasting-hypotheses.html
            text: "Aula 1 - Contrastando Hipóteses"
            target: "_blank"
          - href: content/slides/slides-02-quantifying-uncertainty.html
            text: "Aula 2 - Quantificando a Incerteza"
            target: "_blank"
      - section: "Lab. Informática"
        contents:
          - href: content/computer-lab/lab-01-contrasting-hypotheses.qmd
            text: "Aula 1 - Contrastando Hipóteses"
          - href: content/computer-lab/lab-02-quantifying-uncertainty.qmd
            text: "Aula 2 - Quantificando a Incerteza"
            target: "_blank"
          

# Global format configuration
format:
  html:
    theme:
      light: [cosmo, styles/theme.scss]
      dark: [cosmo, styles/theme-dark.scss]
    toc: true
    number-sections: true
    code-copy: true
    code-overflow: wrap

# Configura projeto para ser executado apenas localmente
execute:
  freeze: auto

bibliography: references.bib