project:
  type: website
  output-dir: _site
  resources:
    - "content/apresentacoes/*.html"
    - "content/apresentacoes/css/**"
    - "content/apresentacoes/imagens/**"
    - "content/apresentacoes/scripts-r/**"

lang: pt

publish:
  method: gh-pages
  repo: FCopf/prob-est-2026

website:
  page-navigation: true
  title: "5290 - PROBABILIDADE E ESTATÍSTICA"
  description: "Materiais, cronograma e recursos da UC Probabilidade e Estatística do Bict Mar — Unifesp."
  site-url: "https://fcopf.github.io/prob-est-2026"

  repo-url: "https://github.com/FCopf/prob-est-2026"
  open-graph: true

  page-footer:
    right: "BACHARELADO INTERDISCIPLINAR EM CIÊNCIA E TECNOLOGIA DO MAR - Bict Mar - Unifesp"
    left: Fabio Cop
    background: "#296354"

  sidebar: 
    background: "#3b8170"
    logo: "imagens/logo.png"
    style: "docked"
    search: true
    align: center
    tools:
      - icon: github
        href: https://github.com/FCopf/prob-est-2026
        text: GitHub da UC
      - icon: book
        href: https://moodlegrad.unifesp.br/
        text: Moodle Graduação
      - icon: terminal
        href: https://colab.research.google.com/drive/
        text: Google Colab
    
    collapse-level: 1
    contents:
      - section: "Informações do curso"
        contents:
          - href: informacoes_curso/plano_ensino.qmd
            text: Plano de Ensino
          - href: index.qmd
            text: Cronograma
          - href: informacoes_curso/bibliografia.qmd
            text: Bibliografia e Links Úteis
      - section: "Leitura Prévia"
        contents:
          - href: content/leitura-previa/index.qmd
            text: "Leitura Obrigatória"
      - section: "Apresentações"
        contents:
          - href: content/apresentacoes/aula-01-contrastando-hipoteses.html
            text: "Aula 1 - Contrastando Hipóteses"
            target: "_blank"
          # - href: content/apresentacoes/aula-02-quantificando-incerteza.html
          #   text: "Aula 2 - Quantificando a Incerteza"
          #   target: "_blank"
          # - href: content/apresentacoes/aula-03-formalizando-incerteza-discretos.html
          #   text: "Aula 3 - Modelos Discretos"
          #   target: "_blank"
          # - href: content/apresentacoes/aula-04-formalizando-incerteza-continuos.html
          #   text: "Aula 4 - Modelos Contínuos"
          #   target: "_blank"
          # - href: content/apresentacoes/aula-06-relacoes-causais.html
          #   text: "Aula 6 - Relações Causais"
          #   target: "_blank"
          # - href: content/apresentacoes/aula-07-distribuicoes-a-priori.html
          #   text: "Aula 7 - Distribuições a Priori"
          #   target: "_blank"
          # - href: content/apresentacoes/aula-08-visualizacao-descricao-dados.html
          #   text: "Aula 8 - Visualização de Dados"
          #   target: "_blank"
          # - href: content/apresentacoes/aula-09-estimacao-bayesiana.html
          #   text: "Aula 9 - Estimação Bayesiana"
          #   target: "_blank"
          # - href: content/apresentacoes/aula-10-regressao-multipla.html
          #   text: "Aula 10 - Regressão Múltipla"
          #   target: "_blank"
          # - href: content/apresentacoes/aula-11-relacoes-nao-lineares.html
          #   text: "Aula 11 - Relações Não Lineares"
          #   target: "_blank"
          # - href: content/apresentacoes/aula-12-comparacao-validacao-modelos.html
          #   text: "Aula 12 - Comparação de Modelos"
          #   target: "_blank"
          # - href: content/apresentacoes/aula-14-modelos-contagem-classificacao.html
          #   text: "Aula 14 - Modelos de Contagem"
          #   target: "_blank"
          # - href: content/apresentacoes/aula-15-modelos-hierarquicos.html
          #   text: "Aula 15 - Modelos Hierárquicos"
          #   target: "_blank"
          # - href: content/apresentacoes/aula-16-dependencias-espaciais-temporais.html
          #   text: "Aula 16 - Dependências Espaciais"
          #   target: "_blank"
      - section: "Lab. Informática"
        contents:
          - href: content/lab_informatica/lab-info-01-contrastando-hipotese.qmd
            text: "Aula 1 - Contrastando Hipóteses"
            target: "_blank"
          # - href: content/lab_informatica/lab-info-02-quantificando-incerteza.qmd
          #   text: "Aula 2 - Quantificando a Incerteza"
          #   target: "_blank"
          # - href: content/lab_informatica/lab-info-03-formalizando-incerteza-discretos.qmd
          #   text: "Aula 3 - Modelos Discretos"
          #   target: "_blank"
          # - href: content/lab_informatica/lab-info-04-formalizando-incerteza-continuos.qmd
          #   text: "Aula 4 - Modelos Contínuos"
          #   target: "_blank"
          # - href: content/lab_informatica/lab-info-06-relacoes-causais.qmd
          #   text: "Aula 6 - Relações Causais"
          #   target: "_blank"
          # - href: content/lab_informatica/lab-info-07-distribuicoes-a-priori.qmd
          #   text: "Aula 7 - Distribuições a Priori"
          #   target: "_blank"
          # - href: content/lab_informatica/lab-info-08-visualizacao-descricao-dados.qmd
          #   text: "Aula 8 - Visualização de Dados"
          #   target: "_blank"
          # - href: content/lab_informatica/lab-info-09-estimacao-bayesiana.qmd
          #   text: "Aula 9 - Estimação Bayesiana"
          #   target: "_blank"
          # - href: content/lab_informatica/lab-info-10-regressao-multipla.qmd
          #   text: "Aula 10 - Regressão Múltipla"
          #   target: "_blank"
          # - href: content/lab_informatica/lab-info-11-relacoes-nao-lineares.qmd
          #   text: "Aula 11 - Relações Não Lineares"
          #   target: "_blank"
          # - href: content/lab_informatica/lab-info-12-comparacao-validacao-modelos.qmd
          #   text: "Aula 12 - Comparação de Modelos"
          #   target: "_blank"
          # - href: content/lab_informatica/lab-info-14-modelos-contagem-classificacao.qmd
          #   text: "Aula 14 - Modelos de Contagem"
          #   target: "_blank"
          # - href: content/lab_informatica/lab-info-15-modelos-hierarquicos.qmd
          #   text: "Aula 15 - Modelos Hierárquicos"
          #   target: "_blank"
          # - href: content/lab_informatica/lab-info-16-dependencias-espaciais-temporais.qmd
          #   text: "Aula 16 - Dependências Espaciais"
          #   target: "_blank"
      - section: "Avaliações"
        contents:
          - href: content/avaliacoes/index.qmd
            text: "Avaliações"
            target: "_blank"

# Global format configuration
format:
  html:
    theme:
      light: [cosmo, styles/theme.scss]
      dark: [cosmo, styles/theme-dark.scss]
    toc: true
    number-sections: true
    code-copy: true
    code-overflow: wrap

# Configura projeto para ser executado apenas localmente
execute:
  freeze: auto

bibliography: references.bib